# -*- coding: utf-8 -*-
"""EDA TASK2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rVHloiv8QN9YvGFHyWUwEbqZpK8AG9MY
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('/content/train.csv')
print(data)

data.shape

data.dtypes

data.head(5)

data.tail()

data.columns

data.info()

data.describe()

data.isnull().sum()

data['Age'] =  data['Age'].fillna(data.mean, inplace = False)

data['Cabin'] = data['Cabin'].fillna(data['Cabin'].mode()[0])

data['Embarked'] = data['Embarked'].fillna(data['Embarked'].mode()[0])

data.isnull().sum()

data['Age'] = pd.to_numeric(data['Age'], errors='coerce').astype('Int64')

plt.boxplot(x = data['Age'])

plt.scatter(data['Pclass'], data['Fare'])
plt.title("Scatter Plot for the Age and Parch")
plt.xlabel("Age")
plt.ylabel("Parch")
plt.show()

pd.crosstab(data['Sex'], data['Survived']).plot(kind="bar")
plt.show()

correlation = data.corr(numeric_only = True)
import seaborn as sns
sns.heatmap(correlation, annot = True)
plt.show()

